version: '3'
services:
  inventory_service:
    image: inventory:latest
    container_name: "inventory"
    restart: unless-stopped
#    depends_on:
#      - service_discovery
    ports:
      - "6969:80"
    networks:
      pad-net:

  renting_service:
    image: rentingservice:latest
    container_name: "renting"
    restart: unless-stopped
    ports:
      - "7979:80"
    networks:
      pad-net:

  redis_db:
    image: redis:latest
    container_name: "redis_cache"
    restart: unless-stopped
    ports:
      - "7379:7379"
    networks:
      pad-net:

  cache_service:
    image: cache:latest
    container_name: "cache"
    restart: unless-stopped
    depends_on:
      - redis_db
    ports:
      - "1234:1234"
    networks:
      pad-net:

  postgres:
    image: postgres:14.5-alpine
    container_name: my_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./InventoryService/InventoryService/Data/db.sql:/docker-entrypoint-initdb.d/inventory.sql
      - ./RentingService/RentingService/Data/db.sql:/docker-entrypoint-initdb.d/renting.sql
    networks:
      pad-net:

  db_pgadmin:
    image: dpage/pgadmin4
    container_name: pad_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=lozovanusilviu@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5481:80"
    networks:
      pad-net:

volumes:
  pg_data:
  pgadmin_data:
networks:
  pad-net: