global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090','renting-first:80','renting-second:80','renting-third:80','inventory-first:80','inventory-second:80','inventory-third:80','gateway:3000','service-discovery:3002','cache:1234']